version: '2'
services:
  # db:
  #   image: postgres:10-alpine
  #   environment:
  #     POSTGRES_USER: sequser
  #     POSTGRES_DB: seqdb
  #     POSTGRES_PASSWORD: seqpasswd
  #     LANG: "C.UTF-8"
  #     TZ: "America/Recife"
  #   volumes:
  #     - pg_dt:/var/lib/postgresql/data
  #   restart: always
  web:
    # depends_on:
    #   - db
    image: nexus.devops.ifrn.edu.br/{{ repository }}:latest
    # volumes:
    #   - web_app:/usr/app/
    ports:
       - "{{ port }}:3000"
    restart: always
    environment:
      # DATABASE_URL: postgres://sequser:seqpasswd@db/seqdb
      LANG: "C.UTF-8"
      TZ: "America/Recife"
# volumes:
#   pg_dt:
#   web_app:
